### ISSUE TITLE
Add `backported` label to PRs when running the backport tool

### ISSUE THREAD

**Issue by spalger** [sqren/backport#147]
How would you feel about supporting configuration that adds a label like `backported` to a PR once the backport PRs have been created? It's a little misleading because the backport PRs haven't been merged, but it's also a good indicator as PRs have a lot more visibility (usually PRs don't go unmerged for too long) and the status of each backport PR is usually listed at the bottom of the history for the source PR...

Thoughts?

cc @FrankHassanabad @spong

**Comment by FrankHassanabad** [comment]
That sounds like an improvement so ++

**Comment by acrewdson** [comment]
+1 for this and also for making the label name configurable in `config.json`

**Comment by sqren** [comment]
Cool, what do you think the option should be called? There is already `label` which is the label added to the backport PRs: 

```js
// Example .backportrc.json
{
  "upstream": "elastic/kibana",
  "branches": [{ "name": "7.x", "checked": true }, "7.4", "7.3"],
  "labels": ["backport"]
}
```

I was thinking about `originalPRLabels`, `statusLabels`, `successLabels`, `postBackportLabels`. None of them are great. Input much appreciated.

**Comment by acrewdson** [comment]
`originalPRLabels` seems pretty good to me, but yeah, it's a tough one

**Comment by brianmcgue** [comment]
GitHub's reference links are useful when it comes to this. And since each commit message in the PR references it's original PR, they _should_ always show up. But this would still be useful when filtering PRs and for quick reference checks 👍 
<img width="754" alt="Screen Shot 2019-09-06 at 11 01 35 AM" src="https://user-images.githubusercontent.com/5863039/64449886-b9f42300-d095-11e9-80a5-f2cb35aec11f.png">

**Comment by sqren** [comment]
@brianmcgue Yes, this is exactly how I determine which commits have been backported:
<img width="627" alt="Screen Shot 2019-09-16 at 14 40 20" src="https://user-images.githubusercontent.com/209966/64958676-fb53b200-d88f-11e9-8978-2b3c491b6c71.png">

This approach is also more accurate since it tells whether a backport PR just has been created (grey) or merged in (green); and to which versions.

@spalger I've [created a PR](https://github.com/sqren/backport/pull/153) that adds the option `backport-created-labels` (I'm open to better naming suggestions).
